apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stanovanja
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: stanovanja
    newName: rg.fr-par.scw.cloud/djnd/stanovanja
    newTag: 'latest'
